export const Users:any = [
    {
        id:1,
        place:"Nellore"
    },
    {
        id:1,
        name:"Chaitanya",
        place:"Nellore"
    },
    {
        id:2,
        name:"Yodha",
        place:"Nellore"
    },
    {
        id:3,
        name:"Surendra",
        place:"Vedayapalem"
    }
];